/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buku;

/**
 *
 * @author Kandang
 */

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import connection.connection;
import buku.Buku;
import mainfrom.MainForm;
import member.Member;
import pinjam.Pinjam;

public class Buku extends javax.swing.JFrame {

    /**
     * Creates new form Buku
     */
    
    Connection conn;
    PreparedStatement ps, ps2;
    ResultSet rs;
    
    public Buku() {
        conn = connection.getconn();
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPengarang = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiMainForm = new javax.swing.JMenuItem();
        jmiPinjam = new javax.swing.JMenuItem();
        jmiAnggota = new javax.swing.JMenuItem();
        jmiBuku = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Buku");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Form Buku");

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Kode Buku");

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Judul Buku");

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Nama Pengarang");

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Penerbit");

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Jumlah Stok");

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sv.jpg"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ed.jpg"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dt.jpg"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tm.jpg"))); // NOI18N
        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cr.jpg"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Judul Buku", "Nama Pengarang", "Penerbit", "Stok"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTampil)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari)))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTampil)
                        .addComponent(btnCari)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenu1.setText("Form");

        jmiMainForm.setText("TampilanAwal");
        jmiMainForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMainFormActionPerformed(evt);
            }
        });
        jMenu1.add(jmiMainForm);

        jmiPinjam.setText("Pinjam Buku");
        jmiPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPinjamActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPinjam);

        jmiAnggota.setText("Anggota");
        jmiAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnggotaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAnggota);

        jmiBuku.setText("Buku");
        jmiBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBukuActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBuku);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if((txtKode.getText().equals(""))||(txtJudul.getText().equals(""))||(txtPengarang.getText().equals(""))||(txtPenerbit.getText().equals(""))||(txtStok.getText().equals(""))){
            JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
        }else{
            String sqlkode = "Insert into koleksi(Kode,Judul,Pengarang,Penerbit,Stock) values ('"+this.txtKode.getText()+"',"+ "'"+this.txtJudul.getText()+"',"+ "'"+this.txtPengarang.getText()+"',"+"'"+this.txtPenerbit.getText()+"',"+"'"+this.txtStok.getText()+"')";
            String sql = "Insert into stok(Kode,Jumlah) values ('"+this.txtKode.getText()+"',"+"'"+this.txtStok.getText()+"')";

                try { //jalankan query tersebut
                   ps = conn.prepareStatement(sqlkode);
                   ps.executeUpdate();
                   ps.close();

                   ps2 = conn.prepareStatement(sql);
                   ps2.executeUpdate();
                   ps2.close();
                   
                   txtKode.setText("");
                   txtJudul.setText("");
                   txtPengarang.setText("");
                   txtPenerbit.setText("");
                   txtStok.setText("");
                   btnEdit.setEnabled(true);
                   btnHapus.setEnabled(true);
                   txtKode.requestFocus();
                   refreshTable();

                   JOptionPane.showMessageDialog(this, "Simpan Berhasil","Informasi",1);
                }catch(SQLException ex) {
                
                   JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());

                   btnEdit.setEnabled(true);
                   btnHapus.setEnabled(true);
                   txtKode.requestFocus();
                   refreshTable();

                }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if((txtKode.getText().equals(""))||(txtJudul.getText().equals(""))||(txtPengarang.getText().equals(""))||(txtPenerbit.getText().equals(""))||(txtStok.getText().equals(""))){
            JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
        }else{            
            try {
                String sqlkode = "Update koleksi SET Judul='"+this.txtJudul.getText()+"'," + "Pengarang='"+this.txtPengarang.getText()+"',"+"Penerbit='"+this.txtPenerbit.getText()+"',"+"Stock='"+this.txtStok.getText()+"'"+"Where Kode='"+this.txtKode.getText()+"'";
                String sql = "Update stok SET Jumlah='"+this.txtStok.getText()+"'"+"Where Kode='"+this.txtKode.getText()+"'";
                ps = conn.prepareStatement(sqlkode);
                ps.executeUpdate();
                ps.close();
                ps2 = conn.prepareStatement(sql);
                ps2.executeUpdate();
                ps2.close();
                JOptionPane.showMessageDialog(this, "Edit Berhasil","Informasi",1);
                txtKode.setText("");
                txtJudul.setText("");
                txtPengarang.setText("");
                txtPenerbit.setText("");
                txtStok.setText("");
                txtKode.requestFocus();

                refreshTable();
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if(txtKode.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Text Kode Kosong","Informasi",1);
            txtKode.requestFocus();
        }else{
            int dialogResult =  JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus akun ini?", "Warning", JOptionPane.YES_NO_OPTION);
            
            if(dialogResult == JOptionPane.YES_OPTION){
            String sqlkode = "Delete from koleksi "+ "Where Kode='"+this.txtKode.getText()+"'";
            String sql = "Delete from stok "+ "Where Kode='"+this.txtKode.getText()+"'";
               try {
                   ps = conn.prepareStatement(sqlkode);
                   ps.executeUpdate();
                   ps.close();

                   ps2 = conn.prepareStatement(sql);
                   ps2.executeUpdate();
                   ps2.close();


                   txtKode.setText("");
                   txtJudul.setText("");
                   txtPengarang.setText("");
                   txtPenerbit.setText("");
                   txtStok.setText("");
                   txtKode.requestFocus();

                   refreshTable();
               } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
               }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        if(txtKode.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Text ID Kosong","Informasi",1);
            txtKode.requestFocus();
        }else{
        
            DefaultTableModel tabelkol = new DefaultTableModel();
            tabelkol.addColumn("Kode Buku");
            tabelkol.addColumn("Judul Buku");
            tabelkol.addColumn("Pengarang");
            tabelkol.addColumn("Penerbit");
            tabelkol.addColumn("Stok");

            try {
                String sql = "Select * from koleksi where Kode like '%" +txtKode.getText()+"%'" +"or Judul like '%" + txtKode.getText() + "%'"; 
                Statement stat = conn.createStatement();
                rs = stat.executeQuery(sql);

                   txtKode.setText("");
                   txtJudul.setText("");
                   txtPengarang.setText("");
                   txtPenerbit.setText("");
                   txtStok.setText("");
                   txtKode.requestFocus();

                   btnHapus.setEnabled(true);
                   btnEdit.setEnabled(true);

                while (rs.next()) {
                    tabelkol.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
                }
               tblData.setModel(tabelkol);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan "+e);
            }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        refreshTable();
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        txtKode.requestFocus();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void jmiMainFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMainFormActionPerformed
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiMainFormActionPerformed

    private void jmiPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPinjamActionPerformed
        new Pinjam().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiPinjamActionPerformed

    private void jmiAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnggotaActionPerformed
        new Member().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiAnggotaActionPerformed

    private void jmiBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBukuActionPerformed
        new Buku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiBukuActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        JOptionPane.showMessageDialog(this, "Klik Menu untuk melihat data Anggota dan data Buku");
    }//GEN-LAST:event_jMenu2MouseClicked

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        DefaultTableModel Df = (DefaultTableModel)tblData.getModel();
        int selectedIndex = tblData.getSelectedRow();
        
        txtKode.setText(Df.getValueAt(selectedIndex, 0).toString());
        txtJudul.setText(Df.getValueAt(selectedIndex, 1).toString());
        txtPengarang.setText(Df.getValueAt(selectedIndex, 2).toString());
        txtPenerbit.setText(Df.getValueAt(selectedIndex, 3).toString());
        txtStok.setText(Df.getValueAt(selectedIndex, 4).toString());
        
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTampil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiAnggota;
    private javax.swing.JMenuItem jmiBuku;
    private javax.swing.JMenuItem jmiMainForm;
    private javax.swing.JMenuItem jmiPinjam;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPengarang;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        DefaultTableModel tabelkoleksi = new DefaultTableModel();
        tabelkoleksi.addColumn("Kode Buku");
        tabelkoleksi.addColumn("Judul Buku");
        tabelkoleksi.addColumn("Pengarang");
        tabelkoleksi.addColumn("Penerbit");
        tabelkoleksi.addColumn("Stok");
        
        try {
            String sql = "select * from koleksi";
            Statement stat = conn.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                tabelkoleksi.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
           tblData.setModel(tabelkoleksi);
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    
}
