/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package member;

/**
 *
 * @author Kandang
 */

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import connection.connection;
import buku.Buku;
import java.text.SimpleDateFormat;
import mainfrom.MainForm;
import member.Member;
import pinjam.Pinjam;

public class Member extends javax.swing.JFrame {

    /**
     * Creates new form Member
     */
    
    Connection conn;
    ResultSet rs;
    PreparedStatement ps;
    String tampilan = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(tampilan);
    
    public Member() {
        conn = connection.getconn();
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        txtPekerjaan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jdTanggalLahir = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiMainForm = new javax.swing.JMenuItem();
        jmiPinjam = new javax.swing.JMenuItem();
        jmiAnggota = new javax.swing.JMenuItem();
        jmiBuku = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Anggota");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Form Anggota");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("ID Anggota");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tangga Lahir");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Jenis Kelamin");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Pekerjaan");

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sv.jpg"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ed.jpg"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dt.jpg"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tm.jpg"))); // NOI18N
        btnTampil.setText("Tampil");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cr.jpg"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Ttl", "Jenis Kelamin", "Pekerjaan"
            }
        ));
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("(YYYY-MM-DD)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnTampil)
                                .addGap(18, 18, 18)
                                .addComponent(btnCari)))))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdTanggalLahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbJenisKelamin, javax.swing.GroupLayout.Alignment.TRAILING, 0, 100, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtNama)
                            .addComponent(txtId))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(jdTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnTampil)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Form");

        jmiMainForm.setText("Tampilan Awal");
        jmiMainForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMainFormActionPerformed(evt);
            }
        });
        jMenu1.add(jmiMainForm);

        jmiPinjam.setText("Pinjam Buku");
        jmiPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiPinjamMouseClicked(evt);
            }
        });
        jmiPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPinjamActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPinjam);

        jmiAnggota.setText("Anggota");
        jmiAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnggotaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAnggota);

        jmiBuku.setText("Buku");
        jmiBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBukuActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBuku);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMainFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMainFormActionPerformed
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiMainFormActionPerformed

    private void jmiPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiPinjamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiPinjamMouseClicked

    private void jmiPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPinjamActionPerformed
        new Pinjam().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiPinjamActionPerformed

    private void jmiAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnggotaActionPerformed
        new Member().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiAnggotaActionPerformed

    private void jmiBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBukuActionPerformed
        new Buku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiBukuActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        JOptionPane.showMessageDialog(this, "Klik Menu untuk melihat data Anggota dan data Buku");
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String tanggal = String.valueOf(fm.format(jdTanggalLahir.getDate()));
        if((txtId.getText().equals(""))||(txtNama.getText().equals(""))||(txtAlamat.getText().equals(""))||(tanggal.equals(""))||(txtPekerjaan.getText().equals(""))){
            JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
        }else {
         String sqlkode="Insert into anggota(Id,Nama,Alamat,Ttl,Jkl,Pekerjaan) values ('"+this.txtId.getText()+"',"+ "'"+this.txtNama.getText()+"',"+ "'"+this.txtAlamat.getText()+"',"+"'"+tanggal+"',"+"'"+this.cbJenisKelamin.getSelectedItem()+"',"+"'"+this.txtPekerjaan.getText()+"')";
            try { //jalankan query tersebut
               ps = conn.prepareStatement(sqlkode);
               ps.executeUpdate();
               ps.close();
               
               //tampilkan data
                refreshTable();
                JOptionPane.showMessageDialog(this, "Simpan Berhasil","Informasi",1);
                cbJenisKelamin.setSelectedItem("Laki-Laki");
                txtId.setText("");
                txtNama.setText("");
                txtAlamat.setText("");
                jdTanggalLahir.setDateFormatString("");
                txtPekerjaan.setText("");
                btnHapus.setEnabled(true);
                btnEdit.setEnabled(true);
                txtId.requestFocus();
           
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String tanggal = String.valueOf(fm.format(jdTanggalLahir.getDate()));
        if((txtId.getText().equals(""))||(txtNama.getText().equals(""))||(txtAlamat.getText().equals(""))||(tanggal.equals(""))||(txtPekerjaan.getText().equals(""))){
                JOptionPane.showMessageDialog(btnSimpan, "Data Ada Yang Kosong", "INFORMASI", WIDTH, null);
        }else{
            
            String sqlkode="Update anggota SET Nama='"+this.txtNama.getText()+"'," + "Alamat='"+this.txtAlamat.getText()+"',"+"Ttl='"+tanggal+"',"+"Jkl='"+this.cbJenisKelamin.getSelectedItem()+"',"+"Pekerjaan='"+this.txtPekerjaan.getText()+"'" + "Where ID='"+this.txtId.getText()+"'";
                try {
                   ps = conn.prepareStatement(sqlkode);
                   ps.executeUpdate();
                   ps.close();
                   
                   JOptionPane.showMessageDialog(this, "Edit Berhasil","Informasi",1);
                   
                   cbJenisKelamin.setSelectedItem("Laki-Laki");
                   txtId.setText("");
                   txtNama.setText("");
                   txtAlamat.setText("");
                   jdTanggalLahir.setDateFormatString("");
                   txtPekerjaan.setText("");
                   btnHapus.setEnabled(true);
                   btnEdit.setEnabled(true);
                   txtId.requestFocus();

                   refreshTable();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
                }
            }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if(txtId.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text ID Kosong","Informasi",1);
              txtId.requestFocus();
        }else{
            String sqlkode="Delete from anggota " + "Where ID='"+this.txtId.getText()+"'";
            try {
               ps = conn.prepareStatement(sqlkode);
               ps.executeUpdate();
               ps.close();
               
               cbJenisKelamin.setSelectedItem("Laki-Laki");
               txtId.setText("");
               txtNama.setText("");
               txtAlamat.setText("");
               jdTanggalLahir.setDateFormatString("");
               txtPekerjaan.setText("");
               txtId.requestFocus();
               refreshTable();
               
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        refreshTable();
        txtId.requestFocus();
        btnHapus.setEnabled(true);
        btnEdit.setEnabled(true);
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        if(txtId.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Text ID Kosong","Informasi",1);
              txtId.requestFocus();
        }else{
            DefaultTableModel tabelanggota = new DefaultTableModel();
            tabelanggota.addColumn("Id");
            tabelanggota.addColumn("Nama");
            tabelanggota.addColumn("Alamat");
            tabelanggota.addColumn("Tanggal Lahir");
            tabelanggota.addColumn("Jenis Kelamin");
            tabelanggota.addColumn("Pekerjaan");
            
            try {
                String sql = "Select * from anggota where Id like '%" +txtId.getText()+"%'" +"or Nama like '%" + txtId.getText() + "%'"; 
                Statement stat = conn.createStatement();
                rs = stat.executeQuery(sql);

                cbJenisKelamin.setSelectedItem("Laki-Laki");
                txtId.setText("");
                txtNama.setText("");
                txtAlamat.setText("");
                jdTanggalLahir.setDateFormatString("");
                txtPekerjaan.setText("");
                btnHapus.setEnabled(true);
                btnEdit.setEnabled(true);
                txtId.requestFocus();
                while (rs.next()) {
                    tabelanggota.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
                }
               tblData.setModel(tabelanggota);
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan ");
            }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        DefaultTableModel Df = (DefaultTableModel)tblData.getModel();
        int selectedIndex = tblData.getSelectedRow();
        String jeniskelamin = (String) cbJenisKelamin.getSelectedItem();
        
        txtId.setText(Df.getValueAt(selectedIndex, 0).toString());
        txtNama.setText(Df.getValueAt(selectedIndex, 1).toString());
        txtAlamat.setText(Df.getValueAt(selectedIndex, 2).toString());
        jdTanggalLahir.setDateFormatString(Df.getValueAt(selectedIndex, 3).toString());
        jeniskelamin.indexOf(Df.getValueAt(selectedIndex, 4).toString());
        txtPekerjaan.setText(Df.getValueAt(selectedIndex, 5).toString());
        
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTampil;
    private javax.swing.JComboBox<String> cbJenisKelamin;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdTanggalLahir;
    private javax.swing.JMenuItem jmiAnggota;
    private javax.swing.JMenuItem jmiBuku;
    private javax.swing.JMenuItem jmiMainForm;
    private javax.swing.JMenuItem jmiPinjam;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPekerjaan;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
    
        DefaultTableModel tabelanggota = new DefaultTableModel();
        tabelanggota.addColumn("Id");
        tabelanggota.addColumn("Nama");
        tabelanggota.addColumn("Alamat");
        tabelanggota.addColumn("TTL");
        tabelanggota.addColumn("Jenis Kelamin");
        tabelanggota.addColumn("Pekerjaan");
        try {
            String sql = "select * from anggota";
            Statement stat = conn.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                tabelanggota.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
           tblData.setModel(tabelanggota);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan "+e.getMessage());
        }

    }
    
}
